pipeline {
  agent any
  
  environment {
    registry = "soaron/devops-test"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
 
  tools {
      nodejs "node"
  }
 
  stages {
    stage('Cloning Git') {
      steps {
        git 'http://35.181.112.241:7990/scm/sam/myrepo.git'
      }
    }

    stage('Build') {
      steps {
        sh 'npm install'
      }
    }

    stage('Test') {
      steps {
        sh 'npm test'
      }
    }

    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
/*
    stage('Deploy Image') {
        steps{
            script {
                docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                }
            }
        }
    }
*/
    stage('Remove Unused docker image') {
        steps{
            sh "docker rmi $registry:$BUILD_NUMBER"
        }
    }
  }
}
